name: Bash Script CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        sudo apt-get update
        sudo apt-get install -y bash

    - name: Execute Bash script
      run: |
        bash test.sh /scripting "error"

